# Generated by Django 4.1.3 on 2022-11-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='is_taken',
        ),
    ]
