# Generated by Django 4.1.3 on 2022-12-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway_app', '0002_remove_donation_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
